[program:eqdkp-api]
directory=/home/ubuntu/eqdkp-api/
command=/home/ubuntu/eqdkp-api/eqdkp-api
redirect_stderr=true
autorestart=true
stdout_logfile=/home/ubuntu/eqdkp-api/eqdkp-api.log
stdout_logfile_maxbytes=5MB
